; IRext AtomS3 Lite — 独立枚举器
; 支持 LittleFS (独立模式) + TCP联机模式 + AP Web终端

[env:atoms3_lite]
platform  = espressif32
board     = m5stack-atoms3
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    adamvr/base64@^1.0.0
    ArduinoJson
    IRremote
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git

lib_ldf_mode = chain+

build_flags =
    -I ./src/ir_decode/include
    -DBOARD_ARDUINO
    -DSEND_PWM_BY_TIMER
    -DNO_LED_FEEDBACK_CODE
    -DRAW_BUFFER_LENGTH=750
    -DBOARD_HAS_PSRAM            ; AtomS3 有外部 PSRAM，显式声明
    -DARDUINO_USB_MODE=1         ; 启用 USB CDC（AtomS3 通过 USB 输出串口）
    -DARDUINO_USB_CDC_ON_BOOT=1  ; 上电即启动 USB CDC Serial
